/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 android.glb s -T -S -k
Files: android.glb [39.01MB] > /Users/stephen/Downloads/android-transformed.glb [514.23KB] (99%)
*/

import React, { useEffect, useRef } from "react";
import { useFrame, useGraph } from "@react-three/fiber";
import { useGLTF, useAnimations } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";
import { Group } from "three";
import { easing } from "maath";

interface IAndorid {
  playbackSpeed?: number;
  isPressed: boolean;
  wireframe?: boolean;
  opacity?: number;
  idle?: boolean;
}

export function Android(props: IAndorid) {
  const {
    playbackSpeed = 1,
    wireframe = true,
    opacity = 0.1,
    idle = false,
  } = props;
  const group = React.useRef<Group>(null);
  const { scene, animations } = useGLTF(
    "/models/android-transformed.glb",
  ) as any;
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone) as any;
  const { actions } = useAnimations(animations, group);

  const materialRef = useRef(materials["Ch36_Body.001"]);
  const playbackSpeedRef = useRef(playbackSpeed);

  useEffect(() => {
    materialRef.current.wireframe = wireframe;
    materialRef.current.transparent = true;
    materialRef.current.opacity = opacity;
  }, [materialRef, wireframe, opacity]);

  useEffect(() => {
    if (actions["run"] && !idle) {
      console.log(actions["run"]);

      // actions["run"].timeScale = playbackSpeed;
      actions["run"]?.play();
    }
  }, [actions, playbackSpeed, idle]);

  useFrame((state, delta) => {
    if (actions["run"]) {
      easing.damp(
        playbackSpeedRef,
        "current",
        props.isPressed ? 0.1 : 1.5,
        0.25,
        delta,
      );
      actions["run"].timeScale = playbackSpeedRef.current;
    }
  });

  return (
    <group ref={group} dispose={null}>
      <group name="Scene">
        <group
          name="android"
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
          castShadow
        >
          <primitive object={nodes.mixamorig1Hips} />
        </group>
        <skinnedMesh
          name="Ch36"
          geometry={nodes.Ch36.geometry}
          // material={materials["Ch36_Body.001"]}
          skeleton={nodes.Ch36.skeleton}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
          castShadow
        >
          <meshStandardMaterial color="#d6d6cf" />
        </skinnedMesh>
      </group>
    </group>
  );
}

useGLTF.preload("/models/android-transformed.glb");
